export const GET_WALLET = "GET_WALLET";
export const GET_WALLETS = "GET_WALLETS";
export const CREATE_WALLET = "CREATE_WALLET";
export const UPDATE_WALLET = "UPDATE_WALLET";
export const DELETE_WALLET = "DELETE_WALLET";