export const RETRIEVE_BAND = "RETRIEVE_BAND";
export const RETRIEVE_BANDS = "RETRIEVE_BANDS";
export const CREATE_BAND = "CREATE_BAND";
export const UPDATE_BAND = "UPDATE_BAND";
export const DELETE_BAND = "DELETE_BAND";